package mnj.ont.model.views.client;

import mnj.ont.model.views.common.POInformationVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 24 11:16:36 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class POInformationVOClient extends ViewUsageImpl implements POInformationVO {
    /**
     * This is the default constructor (do not remove).
     */
    public POInformationVOClient() {
    }

    public void setHeaderClause() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setHeaderClause",null,null);
        return;
    }
}
