package mnj.ont.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 01 19:23:56 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustMnjOntBomHeaderViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CustMnjOntBomHeaderViewImpl() {
    }


    /**
     * Returns the variable value for pBomNo.
     * @return variable value for pBomNo
     */
    public String getpBomNo() {
        return (String)ensureVariableManager().getVariableValue("pBomNo");
    }

    /**
     * Sets <code>value</code> for variable pBomNo.
     * @param value value to bind as pBomNo
     */
    public void setpBomNo(String value) {
        ensureVariableManager().setVariableValue("pBomNo", value);
    }

    /**
     * Returns the variable value for p_style.
     * @return variable value for p_style
     */
    public String getp_style() {
        return (String)ensureVariableManager().getVariableValue("p_style");
    }

    /**
     * Sets <code>value</code> for variable p_style.
     * @param value value to bind as p_style
     */
    public void setp_style(String value) {
        ensureVariableManager().setVariableValue("p_style", value);
    }

    /**
     * Returns the bind variable value for p_userId.
     * @return bind variable value for p_userId
     */
    public String getp_userId() {
        return (String)getNamedWhereClauseParam("p_userId");
    }

    /**
     * Sets <code>value</code> for bind variable p_userId.
     * @param value value to bind as p_userId
     */
    public void setp_userId(String value) {
        setNamedWhereClauseParam("p_userId", value);
    }

    /**
     * Returns the variable value for p_bpo.
     * @return variable value for p_bpo
     */
    public String getp_bpo() {
        return (String)ensureVariableManager().getVariableValue("p_bpo");
    }

    /**
     * Sets <code>value</code> for variable p_bpo.
     * @param value value to bind as p_bpo
     */
    public void setp_bpo(String value) {
        ensureVariableManager().setVariableValue("p_bpo", value);
    }
}
