package mnj.ont.model.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 24 11:16:35 PKT 2015
// ---------------------------------------------------------------------
public interface POInformationVO extends ViewObject {
    void setHeaderClause();
}
